/******************************************************************************/
/****        Generated by IBExpert 2021.2.16.1 1/7/2022 4:19:59 PM         ****/
/******************************************************************************/

/******************************************************************************/
/****     Following SET SQL DIALECT is just for the Database Comparer      ****/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE AREAS (
    ID    INTEGER GENERATED BY DEFAULT AS IDENTITY,
    AREA  VARCHAR(30)
);

CREATE TABLE PRODUCTS (
    ID    INTEGER GENERATED BY DEFAULT AS IDENTITY,
    NAME  VARCHAR(50)
);

CREATE TABLE STATUS (
    ID      INTEGER GENERATED BY DEFAULT AS IDENTITY,
    STATUS  VARCHAR(50)
);

CREATE TABLE SUGGESTIONS (
    ID          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    RECEIVED    TIMESTAMP NOT NULL,
    SUGGESTION  VARCHAR(500) NOT NULL,
    AREA_ID     INTEGER,
    PRODUCT_ID  INTEGER,
    CONTACT     VARCHAR(250),
    EMAIL       VARCHAR(100),
    STATUS_ID   INTEGER NOT NULL,
    COMMENT     BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    SCHEDULED   DATE,
    PUBLISHED   DATE
);

INSERT INTO AREAS (ID, AREA) VALUES (1, 'RTL');
INSERT INTO AREAS (ID, AREA) VALUES (2, 'VCL');
INSERT INTO AREAS (ID, AREA) VALUES (3, 'FMX');
INSERT INTO AREAS (ID, AREA) VALUES (4, 'LCL');
INSERT INTO AREAS (ID, AREA) VALUES (5, 'WEB');


COMMIT WORK;

INSERT INTO PRODUCTS (ID, NAME) VALUES (1, 'TMS Analytics Pack');
INSERT INTO PRODUCTS (ID, NAME) VALUES (2, 'FireDAC');
INSERT INTO PRODUCTS (ID, NAME) VALUES (3, 'TMS FlexCel');
INSERT INTO PRODUCTS (ID, NAME) VALUES (4, 'TMS Scripter');
INSERT INTO PRODUCTS (ID, NAME) VALUES (5, 'TMS FNC Core');
INSERT INTO PRODUCTS (ID, NAME) VALUES (6, 'TMS Web Updater');
INSERT INTO PRODUCTS (ID, NAME) VALUES (7, 'WX Document');


COMMIT WORK;



/******************************************************************************/
/****                       Autoincrement generators                       ****/
/******************************************************************************/

ALTER TABLE AREAS ALTER ID RESTART WITH 5;
ALTER TABLE PRODUCTS ALTER ID RESTART WITH 7;
ALTER TABLE STATUS ALTER ID RESTART WITH 0;
ALTER TABLE SUGGESTIONS ALTER ID RESTART WITH 0;




/******************************************************************************/
/****                             Primary keys                             ****/
/******************************************************************************/

ALTER TABLE AREAS ADD CONSTRAINT PK_AREAS PRIMARY KEY (ID);
ALTER TABLE PRODUCTS ADD CONSTRAINT PK_PRODUCTS PRIMARY KEY (ID);
ALTER TABLE STATUS ADD CONSTRAINT PK_STATUS PRIMARY KEY (ID);
ALTER TABLE SUGGESTIONS ADD CONSTRAINT PK_SUGGESTIONS PRIMARY KEY (ID);


/******************************************************************************/
/****                             Foreign keys                             ****/
/******************************************************************************/

ALTER TABLE SUGGESTIONS ADD CONSTRAINT FK_SUGGESTIONS_1 FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID);
ALTER TABLE SUGGESTIONS ADD CONSTRAINT FK_SUGGESTIONS_2 FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (ID);
ALTER TABLE SUGGESTIONS ADD CONSTRAINT FK_SUGGESTIONS_3 FOREIGN KEY (AREA_ID) REFERENCES AREAS (ID);
